export type LanguageCode = "en" | "pt";

const englishDictionary = {
  calendar: "Calendar",
  common: {
    add: "Add",
    automatic: "Automatic",
    automaticContrast: "Automatic contrast",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    remove: "Remove",
    replace: "Replace",
    reset: "Reset",
    save: "Save",
    search: "Search",
    settings: "Settings",
    show: "Show",
    hide: "Hide",
  },
  navbar: {
    darkMode: "Dark mode",
    lightMode: "Light mode",
    toggleTheme: "Toggle theme",
    chooseLanguage: "Change language",
    languageMenu: "Language",
  },
  period: {
    previousMonth: "Previous month",
    nextMonth: "Next month",
    currentMonth: "Go to current month",
    currentPeriod: "Current period",
    choosePeriod: "Choose a specific month and year",
    chooseYear: "Choose a year",
    chooseMonth: "Choose a month",
    chooseAnotherYear: "Choose another year",
    previousYears: "Show previous years",
    nextYears: "Show next years",
  },
  dashboard: {
    tablesEyebrow: "Tables",
    tablesTitle: "My Tables",
    addTable: "Add new table",
    tableSettings: "Table settings",
    configureTable: "Configure",
    deleteTable: "Delete table",
    deleteTableTitle: "Delete table?",
    deleteTablePrefix: "This will permanently delete",
    thisTable: "this table",
    savingsEyebrow: "Savings",
    savingsTitle: "My Savings",
    saving: "Saving",
    saved: "Saved",
    saveFailed: "Save failed",
    undo: "Undo",
    income: "Income",
    expenses: "Expenses",
    savings: "Savings",
    debt: "Debt",
    customTable: "Custom Table",
    incomeOption: "Create a new income table.",
    expenseOption: "Create a new expenses table.",
    customOption: "Create a blank custom table.",
  },
  grid: {
    drag: "Drag",
    dashboardBlock: "dashboard block",
    orderControls: "order controls",
    moveUp: "Move up",
    moveDown: "Move down",
    resize: "Drag to resize the table",
  },
  table: {
    total: "Total",
    sum: "Sum",
    viewCalculation: "View calculation",
    stages: "Steps",
    result: "Result",
    decimalSeparator: "Decimal separator",
    decimalComma: "Comma (1,23)",
    decimalPoint: "Point (1.23)",
    emptyTitle: "There is no data in this table yet.",
    emptyDescriptionPrefix: "Add the first row to start filling in",
    addFirstRow: "Add first row",
    examplePaycheck: "E.g. Paycheck",
    exampleFormula: "E.g. 2 + 2 or [Salary]",
    write: "Write…",
    dragToReorder: "Drag to reorder",
    customizeIcon: "Customize icon",
    addRowBelow: "Add a new row below",
    repeatNextMonths: "Repeat in future months",
    deleteRow: "Delete row",
    deleteRowTitle: "Delete row?",
    deleteRowPrefix: "This will permanently delete",
    thisRow: "this row",
    rowAdded: "Row added",
    rowRemoved: "Row removed",
    newRow: "New",
    invalidExpression: "Invalid expression",
    editHeaderName: "Edit header name",
    editNameOf: "Edit name of",
    doubleClickEdit: "Double-click to edit",
    dragColumn: "Drag column",
    moveColumn: "Move column",
    formatHeaderCells: "Format header or cells",
    format: "Format",
    resizeColumn: "Resize column",
    columns: {
      icon: "Icon",
      description: "Description",
      current: "This month",
      previous: "Previous month",
      difference: "Difference",
      newColumn: "New column",
    },
  },
  tableSettings: {
    title: "Table settings",
    close: "Close table settings",
    column: "column",
    columns: "columns",
    tableName: "Table name",
    defaultNote: "Only rows marked for the next month are copied. Custom tables are created automatically when they contain at least one marked row.",
    tableColumns: "Table columns",
    rowIcons: "Row icons",
    rowIconsHelp: "Fixed identifier beside the drag handle.",
    background: "background",
    text: "text",
    oneColumnRequired: "A table needs at least one column",
    deleteColumn: "Delete column",
    deleteColumnLabel: "Delete column",
    newColumnType: "New column type",
    textColumn: "Text column",
    createTextColumn: "Create text column",
    valueColumn: "Value or formula column",
    createValueColumn: "Create value column",
    newColumnName: "New column name",
    addColumn: "Add column",
    appearance: "Appearance",
    canvas: "Canvas",
    canvasContent: "Canvas content",
    table: "Table",
    tableContent: "Table content",
    replaceImage: "Replace image",
    addBackgroundImage: "Add background image",
    removeImage: "Remove",
    imageHint: "JPG, PNG or WebP up to 700 KB.",
    resetDefaults: "Reset table defaults",
    kinds: {
      icon: "Icon",
      text: "Text",
      amount: "Value",
      previous: "Previous",
      difference: "Difference",
    },
  },
  formula: {
    customPanels: "Custom panels",
    dashboard: "Formula dashboard",
    addFormula: "Add formula",
    newFormula: "New Formula",
    invalid: "Invalid",
    deleteTitle: "Delete formula?",
    deletePrefix: "This will permanently delete",
    thisFormula: "this formula",
    customizeIcon: "Customize formula icon",
    background: "Formula background",
    name: "Formula name",
    hideVariables: "Hide variables",
    showVariables: "Show variables",
    closeEditor: "Close formula editor",
    customizeCardIcon: "Customize card icon",
    result: "Result",
    variables: "Variables",
    searchVariables: "Search variables",
    variablesHelp: "Type, click or drag variables into the formula.",
    search: "Search",
    mostUsed: "Most used",
    noVariables: "No variables found",
    noVariablesUsed: "No variables used yet",
    formula: "Formula",
    inputPlaceholder: "Type a variable or number",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    totalSavings: "Total Savings",
    balance: "Balance",
    errors: {
      empty: "Formula is empty.",
      unknownToken: "Unknown variable or invalid token:",
      closingParenthesis: "Closing parenthesis without matching opening parenthesis.",
      consecutiveOperators: "Two operators cannot be used in a row.",
      unbalancedParentheses: "Parentheses are not balanced.",
      trailingOperator: "Formula cannot end with an operator.",
      invalidResult: "Formula result is not a valid finite number.",
      calculationFailed: "Formula could not be calculated.",
    },
  },
  variables: {
    title: "Variables",
    description: "Available variables for the current period.",
    search: "Search variables",
    noneFound: "No variables found.",
    variables: "variables",
    used: "used",
    sources: {
      income: "Income",
      expense: "Expense",
      saving: "Saving",
      table: "Table",
      formula: "Formula",
      system: "System",
    },
  },
  colorPicker: {
    automatic: "Automatic",
    useAutomatic: "Use automatic color",
    useColor: "Use",
    customColor: "Custom color",
    chooseCustomColor: "Choose custom color",
    gradient: "Gradient",
    createGradient: "Create gradient",
    start: "Start",
    end: "End",
    angle: "Angle",
    applyGradient: "Apply gradient",
  },
  textConfiguration: {
    format: "Format",
    applyFormattingTo: "Apply formatting to",
    formatHeader: "Format header",
    formatCells: "Format cells",
    clickToChange: "Click to change.",
    fontFamily: "Font family",
    fontSize: "Font size",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    changeTextColor: "Change text color",
    chooseTextColor: "Choose text color",
    resetFormatting: "Reset formatting",
    resetHeader: "Reset header formatting",
    resetCells: "Reset cell formatting",
    alignLeft: "Align left",
    alignCenter: "Align center",
    alignRight: "Align right",
  },
  comments: {
    comment: "Comment",
    editFor: "Edit comment for",
    addTo: "Add comment to",
    closeWithoutSaving: "Close without saving",
    placeholderPrefix: "Write a note about",
    saveShortcut: "Ctrl/⌘ + Enter to save",
    remove: "Remove comment",
    save: "Save comment",
    row: "row",
  },
  savings: {
    addSaving: "Add saving",
    saving: "Saving",
    saved: "Saved",
    delete: "Delete saving",
    customize: "Customize saving",
    newSaving: "New saving",
    progress: "Progress",
    total: "Total",
    goal: "Goal",
    noGoal: "No goal",
    repeat: "Repeat in future months",
    left: "left",
    amount: "Amount",
    amountExample: "E.g. 50",
    note: "Note",
    optional: "Optional",
    addTransaction: "Add movement",
    removeTransaction: "Remove movement",
    recentTransactions: "Recent movements",
    latestTransactions: "Showing latest 6 movements…",
    noTransactions: "No movements yet.",
  },
  iconSelector: {
    customizeRow: "Customize row",
    categories: "Categories",
    addCategories: "Add categories…",
    icons: "Icons",
    searchIcon: "Search icon…",
    customImage: "Custom image",
    browseFiles: "Browse local files",
    chooseFromDevice: "Choose an image from this device",
    clickToChoose: "Click to choose an image from your device",
    uploadWithUrl: "Upload with URL",
    pasteImageLink: "Paste a direct image link",
    removeCustomImage: "Remove custom image",
    recentUploads: "Recent uploads",
    removeRecentImage: "Remove recent image",
    uploadedImage: "Uploaded image",
    localImage: "Local image",
    imageUrl: "Image URL",
    typeUrl: "Type in URL...",
    invalidUrl: "Invalid image URL.",
    pressEnter: "Press Enter to apply.",
    colors: "Colors",
    iconColor: "Icon color",
  },
  genericInput: {
    removeVariable: "Remove",
    formulaVariables: "Formula variables",
    validNumber: "Enter a valid number or calculation.",
    invalidCalculation: "This calculation is not valid.",
  },
  genericPopup: {
    close: "Close popup",
  },
} as const;

type WidenDictionary<T> = {
  [Key in keyof T]: T[Key] extends string ? string : WidenDictionary<T[Key]>;
};

export type LanguageDictionary = WidenDictionary<typeof englishDictionary>;

const portugueseDictionary: LanguageDictionary = {
  calendar: "Calendário",
  common: {
    add: "Adicionar", automatic: "Automático", automaticContrast: "Contraste automático", cancel: "Cancelar",
    close: "Fechar", confirm: "Confirmar", delete: "Apagar", edit: "Editar", remove: "Remover",
    replace: "Substituir", reset: "Repor", save: "Guardar", search: "Pesquisar", settings: "Definições",
    show: "Mostrar", hide: "Esconder",
  },
  navbar: {
    darkMode: "Modo escuro", lightMode: "Modo claro", toggleTheme: "Mudar tema",
    chooseLanguage: "Mudar idioma", languageMenu: "Idioma",
  },
  period: {
    previousMonth: "Mês anterior", nextMonth: "Mês seguinte", currentMonth: "Ir para o mês atual",
    currentPeriod: "Período atual", choosePeriod: "Escolher um mês e ano específicos", chooseYear: "Escolher um ano",
    chooseMonth: "Escolher um mês", chooseAnotherYear: "Escolher outro ano", previousYears: "Mostrar anos anteriores",
    nextYears: "Mostrar anos seguintes",
  },
  dashboard: {
    tablesEyebrow: "Tabelas", tablesTitle: "As minhas tabelas", addTable: "Adicionar tabela",
    tableSettings: "Definições da tabela", configureTable: "Configurar", deleteTable: "Apagar tabela",
    deleteTableTitle: "Apagar tabela?", deleteTablePrefix: "Isto vai apagar permanentemente",
    thisTable: "esta tabela", savingsEyebrow: "Poupanças", savingsTitle: "As minhas poupanças",
    saving: "A guardar", saved: "Guardado", saveFailed: "Falha ao guardar", undo: "Anular",
    income: "Rendimentos", expenses: "Despesas", savings: "Poupanças", debt: "Dívida",
    customTable: "Tabela personalizada", incomeOption: "Criar uma nova tabela de rendimentos.",
    expenseOption: "Criar uma nova tabela de despesas.", customOption: "Criar uma tabela personalizada vazia.",
  },
  grid: {
    drag: "Arrastar", dashboardBlock: "bloco do dashboard", orderControls: "controlos de ordenação", moveUp: "Mover para cima",
    moveDown: "Mover para baixo", resize: "Arrastar para redimensionar a tabela",
  },
  table: {
    total: "Total", sum: "Soma", viewCalculation: "Ver cálculo", stages: "Etapas", result: "Resultado",
    decimalSeparator: "Separador decimal", decimalComma: "Vírgula (1,23)", decimalPoint: "Ponto (1.23)", emptyTitle: "Ainda não há dados nesta tabela.",
    emptyDescriptionPrefix: "Adiciona a primeira linha para começar a preencher",
    addFirstRow: "Adicionar primeira linha", examplePaycheck: "Ex.: Salário",
    exampleFormula: "Ex.: 2 + 2 ou [Salário]", write: "Escrever…", dragToReorder: "Arrastar para reordenar",
    customizeIcon: "Personalizar ícone", addRowBelow: "Adicionar nova linha abaixo",
    repeatNextMonths: "Repetir nos próximos meses", deleteRow: "Apagar linha", deleteRowTitle: "Apagar linha?",
    deleteRowPrefix: "Isto vai apagar permanentemente", thisRow: "esta linha", rowAdded: "Linha adicionada",
    rowRemoved: "Linha removida", newRow: "Nova", invalidExpression: "Expressão inválida", editHeaderName: "Editar nome do cabeçalho",
    editNameOf: "Editar nome de", doubleClickEdit: "Duplo clique para editar", dragColumn: "Arrastar coluna",
    moveColumn: "Mover coluna", formatHeaderCells: "Formatar cabeçalho ou células", format: "Formatar",
    resizeColumn: "Redimensionar coluna",
    columns: { icon: "Ícone", description: "Descrição", current: "Este mês", previous: "Mês anterior", difference: "Diferença", newColumn: "Nova coluna" },
  },
  tableSettings: {
    title: "Definições da tabela", close: "Fechar definições da tabela", column: "coluna", columns: "colunas",
    tableName: "Nome da tabela", defaultNote: "Só são copiadas as linhas marcadas para o mês seguinte. As tabelas personalizadas são criadas automaticamente quando contêm pelo menos uma linha marcada.",
    tableColumns: "Colunas da tabela", rowIcons: "Ícones das linhas", rowIconsHelp: "Identificador fixo junto ao controlo de arrastar.",
    background: "fundo", text: "texto", oneColumnRequired: "A tabela precisa de pelo menos uma coluna",
    deleteColumn: "Apagar coluna", deleteColumnLabel: "Apagar coluna", newColumnType: "Tipo da nova coluna",
    textColumn: "Coluna de texto", createTextColumn: "Criar coluna de texto", valueColumn: "Coluna de valor ou fórmula",
    createValueColumn: "Criar coluna de valor", newColumnName: "Nome da nova coluna", addColumn: "Adicionar coluna",
    appearance: "Aspeto", canvas: "Fundo", canvasContent: "Conteúdo do fundo", table: "Tabela",
    tableContent: "Conteúdo da tabela", replaceImage: "Substituir imagem", addBackgroundImage: "Adicionar imagem de fundo",
    removeImage: "Remover", imageHint: "JPG, PNG ou WebP até 700 KB.", resetDefaults: "Repor definições da tabela",
    kinds: { icon: "Ícone", text: "Texto", amount: "Valor", previous: "Anterior", difference: "Diferença" },
  },
  formula: {
    customPanels: "Painéis personalizados", dashboard: "Dashboard de fórmulas", addFormula: "Adicionar fórmula",
    newFormula: "Nova fórmula", invalid: "Inválido", deleteTitle: "Apagar fórmula?",
    deletePrefix: "Isto vai apagar permanentemente", thisFormula: "esta fórmula", customizeIcon: "Personalizar ícone da fórmula",
    background: "Fundo da fórmula", name: "Nome da fórmula", hideVariables: "Esconder variáveis", showVariables: "Mostrar variáveis",
    closeEditor: "Fechar editor de fórmulas", customizeCardIcon: "Personalizar ícone do cartão", result: "Resultado",
    variables: "Variáveis", searchVariables: "Pesquisar variáveis", variablesHelp: "Escreve, clica ou arrasta variáveis para a fórmula.",
    search: "Pesquisa", mostUsed: "Mais usadas", noVariables: "Nenhuma variável encontrada",
    noVariablesUsed: "Ainda não foram usadas variáveis", formula: "Fórmula", inputPlaceholder: "Escreve uma variável ou número",
    totalIncome: "Total de rendimentos", totalExpenses: "Total de despesas", totalSavings: "Total de poupanças", balance: "Saldo",
    errors: {
      empty: "A fórmula está vazia.", unknownToken: "Variável desconhecida ou elemento inválido:",
      closingParenthesis: "Existe um parêntesis de fecho sem parêntesis de abertura.",
      consecutiveOperators: "Não podem ser usados dois operadores seguidos.", unbalancedParentheses: "Os parêntesis não estão equilibrados.",
      trailingOperator: "A fórmula não pode terminar com um operador.", invalidResult: "O resultado da fórmula não é um número finito válido.",
      calculationFailed: "Não foi possível calcular a fórmula.",
    },
  },
  variables: {
    title: "Variáveis", description: "Variáveis disponíveis para o período atual.", search: "Pesquisar variáveis",
    noneFound: "Nenhuma variável encontrada.", variables: "variáveis", used: "usadas",
    sources: { income: "Rendimento", expense: "Despesa", saving: "Poupança", table: "Tabela", formula: "Fórmula", system: "Sistema" },
  },
  colorPicker: {
    automatic: "Automático", useAutomatic: "Usar cor automática", useColor: "Usar", customColor: "Cor personalizada",
    chooseCustomColor: "Escolher cor personalizada", gradient: "Gradiente", createGradient: "Criar gradiente",
    start: "Início", end: "Fim", angle: "Ângulo", applyGradient: "Aplicar gradiente",
  },
  textConfiguration: {
    format: "Formatar", applyFormattingTo: "Aplicar formatação a", formatHeader: "Formatar cabeçalho",
    formatCells: "Formatar células", clickToChange: "Clica para mudar.", fontFamily: "Tipo de letra",
    fontSize: "Tamanho da fonte", bold: "Negrito", italic: "Itálico", underline: "Sublinhado",
    strikethrough: "Rasurado", changeTextColor: "Alterar cor do texto", chooseTextColor: "Escolher cor do texto",
    resetFormatting: "Repor formatação", resetHeader: "Repor formatação do cabeçalho", resetCells: "Repor formatação das células",
    alignLeft: "Alinhar à esquerda", alignCenter: "Alinhar ao centro", alignRight: "Alinhar à direita",
  },
  comments: {
    comment: "Comentário", editFor: "Editar comentário de", addTo: "Adicionar comentário a",
    closeWithoutSaving: "Fechar sem guardar", placeholderPrefix: "Escreve uma nota sobre", saveShortcut: "Ctrl/⌘ + Enter para guardar",
    remove: "Remover comentário", save: "Guardar comentário", row: "linha",
  },
  savings: {
    addSaving: "Adicionar poupança", saving: "Poupança", delete: "Apagar poupança", customize: "Personalizar poupança",
    saved: "Poupado", newSaving: "Nova poupança", progress: "Progresso", total: "Total", goal: "Objetivo", noGoal: "Sem objetivo",
    repeat: "Repetir nos próximos meses", left: "em falta", amount: "Valor", amountExample: "Ex.: 50", note: "Nota",
    optional: "Opcional", addTransaction: "Adicionar movimento", removeTransaction: "Remover movimento",
    recentTransactions: "Movimentos recentes", latestTransactions: "A mostrar os 6 movimentos mais recentes…",
    noTransactions: "Ainda não existem movimentos.",
  },
  iconSelector: {
    customizeRow: "Personalizar linha", categories: "Categorias", addCategories: "Adicionar categorias…", icons: "Ícones",
    searchIcon: "Pesquisar ícone…", customImage: "Imagem personalizada", browseFiles: "Procurar ficheiros locais",
    chooseFromDevice: "Escolher uma imagem deste dispositivo", clickToChoose: "Clica para escolher uma imagem do dispositivo",
    uploadWithUrl: "Carregar através de URL", pasteImageLink: "Colar uma ligação direta para a imagem",
    removeCustomImage: "Remover imagem personalizada", recentUploads: "Carregamentos recentes",
    removeRecentImage: "Remover imagem recente", uploadedImage: "Imagem carregada", localImage: "Imagem local",
    imageUrl: "URL da imagem", typeUrl: "Escrever URL...", invalidUrl: "URL de imagem inválido.",
    pressEnter: "Prime Enter para aplicar.", colors: "Cores", iconColor: "Cor do ícone",
  },
  genericInput: {
    removeVariable: "Remover", formulaVariables: "Variáveis da fórmula",
    validNumber: "Introduz um número ou cálculo válido.", invalidCalculation: "Este cálculo não é válido.",
  },
  genericPopup: { close: "Fechar popup" },
};

export type Language = {
  code: LanguageCode;
  shortLabel: string;
  localeLabel: string;
  label: string;
  locale: string;
  dictionary: LanguageDictionary;
};

export const LANGUAGES: Record<LanguageCode, Language> = {
  en: { code: "en", shortLabel: "EN", localeLabel: "EN-US", label: "English", locale: "en-US", dictionary: englishDictionary },
  pt: { code: "pt", shortLabel: "PT", localeLabel: "PT-PT", label: "Português", locale: "pt-PT", dictionary: portugueseDictionary },
};

export const LANGUAGE_OPTIONS = Object.values(LANGUAGES);
